[package]
name = "SEIRD_math_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.16.5"
ndarray = "0.15.4"
numpy = "0.16.2"


[lib]
name = "seird_math"
crate-type = ["cdylib"]
